### ISSUE TITLE
Code broadcast with ultrasonic setting + protocol version 1 still audible

### ISSUE THREAD

**Issue by msmoljan** [chirp/chirp-android-examples#10]
Hello, 

We have been using the same config for our iOS and Android app (ultrasonic + protocol version 0). With this configuration, the broadcast is inaudible on iOS, but it is very much noticeable on Android. 

I have been told that this should have been fixed with protocol version 1. However, after updating our config we can still hear the sound clearly during broadcast (although it's somewhat different this time). 

The SDK version we are using is 3.7.0

**Comment by dinuchiriac** [comment]
Hi @msmoljan 
Can you confirm that: 
 - You can send payloads between iOS and Android devices using the same protocol.
 - When sending from iOS, the device is silent however when sending from Android, you can clearly hear the sound.
On some devices with poor speaker quality, the audio can be distorted. If you hear the distortion then it should disappear if you'll decrease the volume a bit when sending.

**Comment by msmoljan** [comment]
Hi @dinuchiriac 

We tested with 3 devices 
- Pixel 3 
- Galaxy S9
- iPhone X 

Sending and receiving payloads worked as expected across devices. 

The sound results were as follows:
- the iPhone sends the payload silently
- the Galaxy also sends the payload silently
- the Pixel 3 makes the aforementioned sound when sending payloads 

So it seems the Pixel 3 is the one with the issue. Since we have to send the signal across a larger distance sometimes, the decreased volume option might not work properly for us (hard to test at this point). We're also performing retries to increase the probability of payload arrival, so the sound is being played repeatedly which is not ideal for the users.

**Comment by javiergcanada** [comment]
Hi. 
I'm experiencing the same problem when trying the app in my BQ Aquaris X. 
The signal is clearly audible and really disturbing.

**Comment by javiergcanada** [comment]
Hi.
I'm experiencing the same problem when trying the app in both my BQ Aquaris X and my Smasung Galaxy Core Prime.
The signal is clearly audible and really disturbing, it doesn't depend on the volume (it only goes away when the volume is all the way down).

**Comment by dinuchiriac** [comment]
Hi @javiergcanada 

Can you please make a recording from the BQ Aquaris X while sending and share it here?  Thanks.

**Comment by javiergcanada** [comment]
Hi @dinuchiriac, here I uploaded a video of the Android demo running on my BQ Aquaris X. The volume was set to approximatelly 75%.
https://drive.google.com/file/d/1tClBalX8r1K8xKMQuv5W-TWRS1i32fMY/view?usp=sharing

**Comment by dinuchiriac** [comment]
Hi @javiergcanada 
It looks like you are using the standard protocol which is audible. The tones you are hearing is the data itself. Please change your config string to ultrasonic if you wish to make it inaudible.
