### ISSUE TITLE
Microphone permission required for broadcasting

### ISSUE THREAD

**Issue by msmoljan** [chirp/chirp-android-examples#7]
Hello, 

The SDK doesn't allow me to `send()` if I don't allow microphone access. 

It would really make sense to enable broadcasts without requiring the microphone permission, e.g. for cases where different receiver and transmitter apps are used and such.

The same is also valid for the iOS version. 

Best regards

**Comment by dinuchiriac** [comment]
Hi @msmoljan 

Thanks for reporting the issue, we are going to update the Audio I/O layer in the next release which will include a fix for the current issue. @joextodd  to confirm the situation on iOS SDK.

We'll update the current thread as soon as we'll have a beta release ready to be tested.

**Comment by msmoljan** [comment]
Hi @dinuchiriac 

Thanks a lot for the quick response! looking forward to the updates :)

**Comment by joextodd** [comment]
Yes this will also be fixed on iOS in the next release [v3.4.4], scheduled for release early next week!

**Comment by msmoljan** [comment]
Hi, any updates on this for the Android version? :)

**Comment by dinuchiriac** [comment]
Hi @msmoljan 

The new version of the Android SDK which includes microphone permissions changes is pretty much done. It will take a couple more days to get it released.

**Comment by msmoljan** [comment]
Sounds good, thanks for the update!

**Comment by dinuchiriac** [comment]
Fixed in v3.7.0

@msmoljan   please update your Gradle dependency to:
`implementation 'io.chirp:chirpsdk:3.7.0'`

The start method is also slightly changed so it accepts 2 boolean arguments: `sender` and `receiver`
`start(sender: Boolean = true, receiver: Boolean = true): ChirpError`
