### ISSUE TITLE
Is it possible to disable the notification sound when broadcasting?

### ISSUE THREAD

**Issue by msmoljan** [chirp/chirp-android-examples#8]
Hello, 

Sorry if this is already in the SDK or if I'm doing something wrong, but I'm not sure how to disable the R2D2-like "chirp" sound that plays every time the data is being broadcasted. I guess this only serves as a notification to the user that something is being transmitted?  

Thanks in advance

**Comment by joextodd** [comment]
Hi @msmoljan 

Chirp actually uses sound to transfer data, you can read more about Chirp at our developer hub [here](https://developers.chirp.io/docs).

To effectively disable the sound, you can use an `ultrasonic` configuration which will be inaudible to the human ear.

**Comment by msmoljan** [comment]
Thanks for clarifying! I was roughly aware of how Chirp works, but I've mistaken the sound played for a notification rather than it being the actual encoded data. I also thought we were already using ultrasonic sound, but it seems that hasn't been the case. Cheers!
